// Dummy data for businesses
export const businessData = [
  {
    id: "1",
    name: "Ecliptic Tech Solutions",
    category: "Technology",
    categories: ["Technology", "Consulting", "Software Development"],
    rating: 4.7,
    reviewCount: 128,
    address: "123 Tech Avenue, San Francisco, CA",
    phone: "(415) 555-7890",
    email: "contact@ecliptictech.com",
    website: "https://ecliptictech.com",
    hours: {
      monday: "9:00 AM - 6:00 PM",
      tuesday: "9:00 AM - 6:00 PM",
      wednesday: "9:00 AM - 6:00 PM",
      thursday: "9:00 AM - 6:00 PM",
      friday: "9:00 AM - 5:00 PM",
      saturday: "Closed",
      sunday: "Closed",
    },
    description:
      "Leading technology consulting firm specializing in software development, cloud solutions, and digital transformation.",
    services: [
      "Custom Software Development",
      "Cloud Migration & Solutions",
      "Digital Transformation Consulting",
      "UI/UX Design",
      "Mobile App Development",
      "Enterprise Solutions",
    ],
    social: {
      facebook: "https://facebook.com/ecliptictech",
      twitter: "https://twitter.com/ecliptictech",
      linkedin: "https://linkedin.com/company/ecliptictech",
      instagram: "https://instagram.com/ecliptictech",
    },
    images: ["/business-1.jpg", "/business-2.jpg", "/business-3.jpg"],
    location: {
      lat: 37.7749,
      lng: -122.4194,
    },
    featured: true,
    owner: {
      name: "Michael Johnson",
      position: "CEO & Founder",
      photo: "/owner-1.jpg",
    },
    yearEstablished: 2015,
  },
  {
    id: "2",
    name: "Coastal Cafe",
    category: "Restaurant",
    categories: ["Restaurant", "Cafe", "Bakery"],
    rating: 4.2,
    reviewCount: 89,
    address: "456 Ocean Drive, San Francisco, CA",
    phone: "(415) 555-1234",
    email: "info@coastalcafe.com",
    website: "https://coastalcafe.com",
    hours: {
      monday: "7:00 AM - 8:00 PM",
      tuesday: "7:00 AM - 8:00 PM",
      wednesday: "7:00 AM - 8:00 PM",
      thursday: "7:00 AM - 8:00 PM",
      friday: "7:00 AM - 9:00 PM",
      saturday: "8:00 AM - 9:00 PM",
      sunday: "8:00 AM - 6:00 PM",
    },
    description: "A cozy waterfront cafe serving fresh pastries, specialty coffee, and light meals with ocean views.",
    services: [
      "Breakfast & Brunch",
      "Specialty Coffee",
      "Fresh Pastries",
      "Light Lunch Options",
      "Catering Services",
      "Private Events",
    ],
    social: {
      facebook: "https://facebook.com/coastalcafe",
      instagram: "https://instagram.com/coastalcafe",
      twitter: "https://twitter.com/coastalcafe",
    },
    images: ["/cafe-1.jpg", "/cafe-2.jpg", "/cafe-3.jpg"],
    location: {
      lat: 37.7833,
      lng: -122.4167,
    },
    featured: false,
    owner: {
      name: "Sarah Williams",
      position: "Owner & Head Chef",
      photo: "/owner-2.jpg",
    },
    yearEstablished: 2018,
  },
  {
    id: "3",
    name: "Urban Fitness Center",
    category: "Health",
    categories: ["Health", "Fitness", "Gym"],
    rating: 4.5,
    reviewCount: 112,
    address: "789 Fitness Lane, San Francisco, CA",
    phone: "(415) 555-5678",
    email: "info@urbanfitness.com",
    website: "https://urbanfitness.com",
    hours: {
      monday: "6:00 AM - 10:00 PM",
      tuesday: "6:00 AM - 10:00 PM",
      wednesday: "6:00 AM - 10:00 PM",
      thursday: "6:00 AM - 10:00 PM",
      friday: "6:00 AM - 9:00 PM",
      saturday: "7:00 AM - 8:00 PM",
      sunday: "8:00 AM - 6:00 PM",
    },
    description: "State-of-the-art fitness center offering personal training, group classes, and premium equipment.",
    services: [
      "Personal Training",
      "Group Fitness Classes",
      "Cardio Equipment",
      "Strength Training",
      "Yoga & Pilates",
      "Nutrition Counseling",
    ],
    social: {
      facebook: "https://facebook.com/urbanfitness",
      instagram: "https://instagram.com/urbanfitness",
      twitter: "https://twitter.com/urbanfitness",
    },
    images: ["/fitness-1.jpg", "/fitness-2.jpg", "/fitness-3.jpg"],
    location: {
      lat: 37.7749,
      lng: -122.4194,
    },
    featured: true,
    owner: {
      name: "Alex Rodriguez",
      position: "Fitness Director",
      photo: "/owner-3.jpg",
    },
    yearEstablished: 2016,
  },
  {
    id: "4",
    name: "Bright Horizons Daycare",
    category: "Education",
    categories: ["Education", "Childcare", "Preschool"],
    rating: 4.8,
    reviewCount: 75,
    address: "101 Child Street, San Francisco, CA",
    phone: "(415) 555-9012",
    email: "contact@brighthorizons.com",
    website: "https://brighthorizons.com",
    hours: {
      monday: "7:00 AM - 6:00 PM",
      tuesday: "7:00 AM - 6:00 PM",
      wednesday: "7:00 AM - 6:00 PM",
      thursday: "7:00 AM - 6:00 PM",
      friday: "7:00 AM - 6:00 PM",
      saturday: "Closed",
      sunday: "Closed",
    },
    description:
      "A nurturing childcare center providing early education and development programs for children ages 6 weeks to 5 years.",
    services: [
      "Infant Care",
      "Toddler Programs",
      "Preschool Education",
      "After-School Care",
      "Summer Programs",
      "Parent Resources",
    ],
    social: {
      facebook: "https://facebook.com/brighthorizons",
      instagram: "https://instagram.com/brighthorizons",
    },
    images: ["/daycare-1.jpg", "/daycare-2.jpg", "/daycare-3.jpg"],
    location: {
      lat: 37.7749,
      lng: -122.4194,
    },
    featured: false,
    owner: {
      name: "Emily Chen",
      position: "Director",
      photo: "/owner-4.jpg",
    },
    yearEstablished: 2012,
  },
  {
    id: "5",
    name: "Evergreen Landscaping",
    category: "Services",
    categories: ["Services", "Landscaping", "Garden"],
    rating: 4.3,
    reviewCount: 64,
    address: "202 Garden Road, San Francisco, CA",
    phone: "(415) 555-3456",
    email: "info@evergreenlandscaping.com",
    website: "https://evergreenlandscaping.com",
    hours: {
      monday: "8:00 AM - 5:00 PM",
      tuesday: "8:00 AM - 5:00 PM",
      wednesday: "8:00 AM - 5:00 PM",
      thursday: "8:00 AM - 5:00 PM",
      friday: "8:00 AM - 5:00 PM",
      saturday: "9:00 AM - 2:00 PM",
      sunday: "Closed",
    },
    description:
      "Professional landscaping services for residential and commercial properties, specializing in sustainable garden design.",
    services: [
      "Landscape Design",
      "Garden Maintenance",
      "Irrigation Systems",
      "Hardscape Installation",
      "Tree Services",
      "Seasonal Planting",
    ],
    social: {
      facebook: "https://facebook.com/evergreenlandscaping",
      instagram: "https://instagram.com/evergreenlandscaping",
    },
    images: ["/landscaping-1.jpg", "/landscaping-2.jpg", "/landscaping-3.jpg"],
    location: {
      lat: 37.7749,
      lng: -122.4194,
    },
    featured: false,
    owner: {
      name: "David Martinez",
      position: "Owner",
      photo: "/owner-5.jpg",
    },
    yearEstablished: 2010,
  },
  {
    id: "6",
    name: "Metro Dental Clinic",
    category: "Healthcare",
    categories: ["Healthcare", "Dental", "Medical"],
    rating: 4.6,
    reviewCount: 93,
    address: "303 Smile Avenue, San Francisco, CA",
    phone: "(415) 555-7890",
    email: "appointments@metrodental.com",
    website: "https://metrodental.com",
    hours: {
      monday: "9:00 AM - 5:00 PM",
      tuesday: "9:00 AM - 5:00 PM",
      wednesday: "9:00 AM - 5:00 PM",
      thursday: "9:00 AM - 5:00 PM",
      friday: "9:00 AM - 4:00 PM",
      saturday: "10:00 AM - 2:00 PM",
      sunday: "Closed",
    },
    description:
      "Comprehensive dental care with the latest technology and a focus on patient comfort and satisfaction.",
    services: [
      "General Dentistry",
      "Cosmetic Dentistry",
      "Orthodontics",
      "Periodontics",
      "Pediatric Dentistry",
      "Emergency Dental Care",
    ],
    social: {
      facebook: "https://facebook.com/metrodental",
      instagram: "https://instagram.com/metrodental",
      twitter: "https://twitter.com/metrodental",
    },
    images: ["/dental-1.jpg", "/dental-2.jpg", "/dental-3.jpg"],
    location: {
      lat: 37.7749,
      lng: -122.4194,
    },
    featured: true,
    owner: {
      name: "Dr. Jennifer Lee",
      position: "Lead Dentist",
      photo: "/owner-6.jpg",
    },
    yearEstablished: 2008,
  },
  {
    id: "7",
    name: "Sunset Boutique",
    category: "Retail",
    categories: ["Retail", "Fashion", "Clothing"],
    rating: 4.4,
    reviewCount: 57,
    address: "404 Fashion Street, San Francisco, CA",
    phone: "(415) 555-2345",
    email: "hello@sunsetboutique.com",
    website: "https://sunsetboutique.com",
    hours: {
      monday: "10:00 AM - 7:00 PM",
      tuesday: "10:00 AM - 7:00 PM",
      wednesday: "10:00 AM - 7:00 PM",
      thursday: "10:00 AM - 7:00 PM",
      friday: "10:00 AM - 8:00 PM",
      saturday: "10:00 AM - 8:00 PM",
      sunday: "11:00 AM - 6:00 PM",
    },
    description:
      "Curated fashion boutique offering unique clothing, accessories, and gifts from independent designers.",
    services: ["Women's Clothing", "Men's Apparel", "Accessories", "Jewelry", "Personal Styling", "Gift Registry"],
    social: {
      facebook: "https://facebook.com/sunsetboutique",
      instagram: "https://instagram.com/sunsetboutique",
      pinterest: "https://pinterest.com/sunsetboutique",
    },
    images: ["/boutique-1.jpg", "/boutique-2.jpg", "/boutique-3.jpg"],
    location: {
      lat: 37.7749,
      lng: -122.4194,
    },
    featured: false,
    owner: {
      name: "Olivia Parker",
      position: "Founder & Buyer",
      photo: "/owner-7.jpg",
    },
    yearEstablished: 2017,
  },
  {
    id: "8",
    name: "Golden Gate Law Firm",
    category: "Legal",
    categories: ["Legal", "Professional Services", "Law"],
    rating: 4.9,
    reviewCount: 42,
    address: "505 Justice Road, San Francisco, CA",
    phone: "(415) 555-6789",
    email: "contact@goldengatelaw.com",
    website: "https://goldengatelaw.com",
    hours: {
      monday: "9:00 AM - 5:00 PM",
      tuesday: "9:00 AM - 5:00 PM",
      wednesday: "9:00 AM - 5:00 PM",
      thursday: "9:00 AM - 5:00 PM",
      friday: "9:00 AM - 5:00 PM",
      saturday: "By appointment",
      sunday: "Closed",
    },
    description:
      "Full-service law firm providing expert legal counsel for individuals and businesses across various practice areas.",
    services: [
      "Corporate Law",
      "Real Estate Law",
      "Intellectual Property",
      "Family Law",
      "Estate Planning",
      "Litigation",
    ],
    social: {
      facebook: "https://facebook.com/goldengatelaw",
      linkedin: "https://linkedin.com/company/goldengatelaw",
      twitter: "https://twitter.com/goldengatelaw",
    },
    images: ["/law-1.jpg", "/law-2.jpg", "/law-3.jpg"],
    location: {
      lat: 37.7749,
      lng: -122.4194,
    },
    featured: false,
    owner: {
      name: "Robert Thompson",
      position: "Managing Partner",
      photo: "/owner-8.jpg",
    },
    yearEstablished: 2005,
  },
]

// Featured businesses (subset of all businesses)
export const featuredBusinessData = businessData.filter((business) => business.featured)
